# Generated by Django 5.1.3 on 2024-11-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_moisture', models.TextField()),
                ('illuminance', models.TextField()),
                ('humidity', models.TextField()),
                ('temperature', models.TextField()),
            ],
        ),
    ]
