# Generated by Django 5.1.3 on 2024-11-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantdata',
            name='humidity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='illuminance',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='soil_moisture',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='plantdata',
            name='temperature',
            field=models.CharField(max_length=10),
        ),
    ]
